# Generated by Django 2.1.5 on 2019-01-23 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190120_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '栏目', 'verbose_name_plural': '栏目'},
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogimg', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Category', verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=16, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub',
            field=models.DateField(auto_now_add=True, verbose_name='评论时间'),
        ),
    ]
