# Generated by Django 2.1.5 on 2019-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20190123_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('content', models.CharField(max_length=64, verbose_name='内容')),
                ('status', models.CharField(choices=[('line', '是'), ('notline', '否')], default='line', max_length=8, verbose_name='上线')),
            ],
            options={
                'verbose_name': '欢迎语',
                'verbose_name_plural': '欢迎语',
            },
        ),
    ]
