# Generated by Django 2.1.5 on 2019-01-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_welcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='status',
            field=models.CharField(choices=[('line', '是'), ('notline', '否')], max_length=8, verbose_name='上线'),
        ),
    ]
