# Generated by Django 2.1.5 on 2019-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxyip', models.CharField(max_length=32, verbose_name='IP地址')),
                ('proxyport', models.CharField(max_length=32, verbose_name='端口')),
                ('proxyaddress', models.CharField(max_length=32, verbose_name='地址')),
                ('proxyhide', models.CharField(max_length=32, verbose_name='隐匿性')),
                ('proxytype', models.CharField(max_length=32, verbose_name='类型')),
                ('proxyspeed', models.CharField(max_length=32, verbose_name='速度')),
                ('proxylink', models.CharField(max_length=32, verbose_name='连接速度')),
                ('proxylive', models.CharField(max_length=32, verbose_name='存活时间')),
                ('proxycheck', models.CharField(max_length=32, verbose_name='验证时间')),
            ],
            options={
                'verbose_name': '代理IP',
                'verbose_name_plural': '代理IP',
            },
        ),
    ]
