# Generated by Django 2.1.5 on 2019-01-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proxy',
            new_name='AgentList',
        ),
    ]
