# Generated by Django 2.1.5 on 2019-01-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentlist',
            name='pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='爬取时间'),
        ),
    ]
