# Generated by Django 2.1.5 on 2019-01-27 17:04

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basicinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32, verbose_name='性别')),
                ('moblie', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('location', models.CharField(max_length=32, verbose_name='所在地点')),
                ('house', models.CharField(max_length=32, verbose_name='户籍')),
                ('marriage', models.CharField(choices=[('yes', '是'), ('no', '否')], default='否', max_length=32, verbose_name='是否结婚')),
                ('worktime', models.DateField(verbose_name='开始工作时间')),
                ('job', models.CharField(max_length=32, verbose_name='求职岗位')),
                ('state', models.CharField(choices=[('service', '在职，看看新机会'), ('leave', '正在离职，一个月内到岗'), ('leaved', '已离职，随时到岗')], default='在职，看看新机会', max_length=32, verbose_name='当前状态')),
            ],
            options={
                'verbose_name': '基本资料',
                'verbose_name_plural': '基本资料',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=32, verbose_name='院校')),
                ('department', models.CharField(max_length=32, verbose_name='院系')),
                ('profession', models.CharField(max_length=32, verbose_name='专业')),
                ('degree', models.CharField(choices=[('primary', '小学'), ('junior', '初中'), ('high', '高中'), ('college', '大专'), ('specialist', '专科'), ('bachelor', '本科'), ('postgraduate', '研究生'), ('doctor', '博士')], max_length=32, verbose_name='学历')),
                ('unified', models.CharField(choices=[('yes', '是'), ('no', '否')], max_length=32, verbose_name='是否统招')),
                ('stating', models.DateField(verbose_name='就读时间')),
                ('ending', models.DateField(verbose_name='毕业时间')),
                ('petname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '教育背景',
                'verbose_name_plural': '教育背景',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluations', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='自我评价')),
                ('petname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '自我评价',
                'verbose_name_plural': '自我评价',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='技能特长')),
                ('petname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '技能特长',
                'verbose_name_plural': '技能特长',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thingname', models.CharField(max_length=32, verbose_name='项目名称')),
                ('thingposition', models.CharField(max_length=32, verbose_name='项目职务')),
                ('thingdescription', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='项目描述')),
                ('thingresponsibility', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='项目职责')),
                ('thingperformance', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='项目业绩')),
                ('entertime', models.DateField(verbose_name='开始日期')),
                ('leavetime', models.DateField(blank=True, null=True, verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
            },
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32, verbose_name='公司名称')),
                ('position', models.CharField(max_length=32, verbose_name='职位')),
                ('scale', models.CharField(choices=[('fifty', '50人以下'), ('hundred', '50-200人'), ('thousand', '200-1000人'), ('more', '1000人以上')], max_length=32, verbose_name='规模')),
                ('industry', models.CharField(max_length=32, verbose_name='行业')),
                ('salary', models.CharField(max_length=32, verbose_name='薪酬')),
                ('location', models.CharField(max_length=32, verbose_name='工作地点')),
                ('duties', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='职责业绩')),
                ('entertime', models.DateField(verbose_name='入职日期')),
                ('leavetime', models.DateField(blank=True, null=True, verbose_name='离职日期')),
                ('petname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='姓名')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='workname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Worklist', verbose_name='公司'),
        ),
    ]
