# Generated by Django 2.1.5 on 2019-01-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='petname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='归属用户'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='petname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='归属用户'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='petname',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='归属用户'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='workname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Worklist', verbose_name='归属公司'),
        ),
        migrations.AlterField(
            model_name='worklist',
            name='petname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Basicinfo', verbose_name='归属用户'),
        ),
    ]
